name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # or master, depending on your default branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 3: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build and push the Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: your-dockerhub-username/food-delivery:latest  # Replace with your Docker Hub repo

    # Step 5: Optional: Deploy to your server
    - name: Deploy to server
      run: |
        # Add deployment steps here (e.g., SSH to your server, pull latest image, etc.)
